[build]
  publish = "."

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
